#!/usr/bin/env ruby

exit unless rails_env = (ENV['RAILS_ENV'] || Rails.env)

# Called after the irb session is initialized and Rails has been loaded

IRB.conf[:IRB_RC] = Proc.new do
  ActiveRecord::Base.logger = Logger.new(STDOUT)
end if defined?(ActiveRecord)

# Rails3
if defined?(::Rails) && Rails.version.split('.').first.to_i >= 3
  include Rails.application.routes.url_helpers
  default_url_options[:host] = Rails.application.class.parent_name.downcase
end

private

def sql(query)
  if query =~ /^select/
    ActiveRecord::Base.connection.select_all query
  else
    ActiveRecord::Base.connection.execute query
  end
end

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end
