#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

set -euo pipefail

API=~/.dotfiles/share/transmission/api

SESSION=$("$API" 2> /dev/null || true)

"$API" --session="$SESSION" -d '{"method": "session-stats"}' |
  jq --arg fetched_at "$(date '+%F %T')" '{
    $fetched_at,
    total_torrents: .arguments.torrentCount,
    leeching_torrents: (.arguments.torrentCount - .arguments.activeTorrentCount),
    active_torrents: .arguments.activeTorrentCount,
    download_speed: .arguments.downloadSpeed,
    upload_speed: .arguments.uploadSpeed
  }'
