#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

CONTAINER=network.priddle.transmission
FEEDS=/volume1/docker/network.priddle.home/public/feeds/openvpn

[[ ! -d "$FEEDS" ]] && mkdir "$FEEDS"

rm -f "$FEEDS/up"

~/.dotfiles/share/transmission/openvpn-ips |
  tee "$FEEDS/ips.json.tmp"

mv -f "$FEEDS/ips.json.tmp" "$FEEDS/ips.json"

REAL_IP="$(jq .real_ip "$FEEDS/ips.json")"
OPENVPN_IP="$(jq .openvpn_ip "$FEEDS/ips.json")"

if [[ "$OPENVPN_IP" != UNKNOWN ]] && [[ "$OPENVPN_IP" != "$REAL_IP" ]]; then
  touch "$FEEDS/up"
fi
