#!/usr/bin/env bash

FEEDS=/volume1/docker/network.priddle.home/public/feeds
DIR="$FEEDS/vnstat"
BIN=~/.dotfiles/share/opnsense/bandwidth-json

hourly=$("$BIN" hourly | tee "$DIR/hourly.json.tmp")
daily=$("$BIN" daily | tee "$DIR/daily.json.tmp" "$DIR/now.json.tmp")
monthly=$("$BIN" monthly | tee "$DIR/monthly.json.tmp")
yearly=$("$BIN" yearly | tee "$DIR/yearly.json.tmp")

jq -n \
  --arg     fetched_at "$(date '+%F %T')" \
  --argjson hourly     "$hourly" \
  --argjson daily      "$daily" \
  --argjson monthly    "$monthly" \
  --argjson yearly     "$yearly" \
  '{
    $fetched_at,
    hourly:  ($hourly | del(.fetched_at)),
    daily:   ($daily | del(.fetched_at)),
    monthly: ($monthly | del(.fetched_at)),
    yearly:  ($yearly | del(.fetched_at))
  }' | tee "$DIR/all.json.tmp"

mv -f "$DIR/hourly.json.tmp" "$DIR/hourly.json"
mv -f "$DIR/daily.json.tmp" "$DIR/daily.json"
mv -f "$DIR/now.json.tmp" "$DIR/now.json"
mv -f "$DIR/monthly.json.tmp" "$DIR/monthly.json"
mv -f "$DIR/yearly.json.tmp" "$DIR/yearly.json"
mv -f "$DIR/all.json.tmp" "$DIR/all.json"
