#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

set -euo pipefail

FEEDS=/volume1/docker/network.priddle.home/public/feeds/pihole

~/.dotfiles/opt/pihole-cli/bin/pihole-summary | tee "$FEEDS/all.json.tmp"

mv "$FEEDS/all.json.tmp" "$FEEDS/all.json"
