#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

set -euo pipefail

check_cert() {
  local domain="$1"
  local port="${2:-443}"
  local expiry

  expiry=$(echo | openssl s_client \
    -servername "$domain" \
    -connect "$domain:$port" 2>/dev/null |
    openssl x509 -noout -enddate |
    sed 's/.*=//'
  )

  jq -Rn \
    --arg domain "$domain" \
    --arg expiry "$expiry" \
    '{
      "\($domain)": ($expiry | strptime("%b %d %H:%M:%S %Y %Z") | strftime("%FT%T.000%z"))
    }'
}

FEEDS=/volume1/docker/network.priddle.home/public/feeds/ssl

[[ ! -d "$FEEDS" ]] && mkdir "$FEEDS"

{
  check_cert router.priddle.network
  check_cert dns1.priddle.network
  check_cert dns2.priddle.network
  check_cert emby.priddle.network 8920
  check_cert josh.fail
  check_cert priddle.xyz
  check_cert recipes.priddle.xyz

  # This is a wildcard
  check_cert scarif.priddle.network | jq '
    .["*.priddle.network"] = .["scarif.priddle.network"] |
      del(.["scarif.priddle.network"])
  '
} |
  jq -s add |
  tee "$FEEDS/status.json.tmp"

mv -f "$FEEDS/status.json.tmp" "$FEEDS/status.json"
