#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

set -euo pipefail

FEEDS=/volume1/docker/network.priddle.home/public/feeds

[[ ! -d "$FEEDS/syno" ]] && mkdir "$FEEDS/syno"

~/.dotfiles/share/syno/resource-usage |
  tee "$FEEDS/syno/stats.json.tmp"

mv -f "$FEEDS/syno/stats.json.tmp" "$FEEDS/syno/stats.json"
