#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

FEEDS=/volume1/docker/network.priddle.home/public/feeds/vnstat

[[ ! -d "$FEEDS" ]] && mkdir "$FEEDS"

BIN=~/.dotfiles/share/opnsense/bandwidth-json

FHOUR="$(date '+%F-%H')00"
FDAY="$(date '+%F')"
FMONTH="$(date '+%Y-%m')"
FYEAR="$(date '+%Y')"

HOURLY_FILES=(
  "$FEEDS/hourly/now.json.tmp"
  "$FEEDS/hourly/$FDAY/$FHOUR.json.tmp"
)

DAILY_FILES=(
  "$FEEDS/daily/now.json.tmp"
  "$FEEDS/daily/$FYEAR/$FDAY.json.tmp"
)

MONTHLY_FILES=(
  "$FEEDS/monthly/now.json.tmp"
  "$FEEDS/monthly/$FYEAR/$FMONTH.json.tmp"
)

YEARLY_FILES=(
  "$FEEDS/yearly/now.json.tmp"
  "$FEEDS/yearly/$FYEAR.json.tmp"
)

for f in "${HOURLY_FILES[@]}" "${DAILY_FILES[@]}" "${MONTHLY_FILES[@]}" "${YEARLY_FILES[@]}"; do
  mkdir -p "$(dirname "$f")"
done

hourly=$("$BIN" hourly | tee "${HOURLY_FILES[@]}")
daily=$("$BIN" daily | tee "${DAILY_FILES[@]}")
monthly=$("$BIN" monthly | tee "${MONTHLY_FILES[@]}")
yearly=$("$BIN" yearly | tee "${YEARLY_FILES[@]}")

jq -n \
  --arg     fetched_at "$(date '+%F %T')" \
  --argjson hourly     "$hourly" \
  --argjson daily      "$daily" \
  --argjson monthly    "$monthly" \
  --argjson yearly     "$yearly" \
  '{
    $fetched_at,
    hourly:  ($hourly | del(.fetched_at)),
    daily:   ($daily | del(.fetched_at)),
    monthly: ($monthly | del(.fetched_at)),
    yearly:  ($yearly | del(.fetched_at))
  }' | tee "$FEEDS/now.json.tmp"

for f in "$FEEDS/now.json.tmp" "${HOURLY_FILES[@]}" "${DAILY_FILES[@]}" "${MONTHLY_FILES[@]}" "${YEARLY_FILES[@]}"; do
  mv -f "$f" "${f%%.tmp}"
done
