#!/usr/bin/env bash

check_cert() {
  local domain="$1"
  local port="${2:-443}"
  local expiry

  expiry=$(echo | openssl s_client \
    -servername "$domain" \
    -connect "$domain:$port" 2>/dev/null |
    openssl x509 -noout -enddate |
    sed 's/.*=//'
  )

  jq -Rn \
    --arg domain "$domain" \
    --arg expiry "$expiry" \
    '{
      "\($domain)": ($expiry | strptime("%b %d %H:%M:%S %Y %Z") | strftime("%F %TZ%z"))
    }'
}

FEEDS=/volume1/docker/network.priddle.home/public/feeds

{ check_cert router.priddle.network    | tee "$FEEDS/ssl/router.json.tmp"
  check_cert dns1.priddle.network      | tee "$FEEDS/ssl/dns1.json.tmp"
  check_cert dns2.priddle.network      | tee "$FEEDS/ssl/dns2.json.tmp"
  check_cert scarif.priddle.network    | tee "$FEEDS/ssl/scarif.json.tmp"
  check_cert emby.priddle.network 8920 | tee "$FEEDS/ssl/emby.json.tmp"

  jq '
    .["*.priddle.network"] = .["scarif.priddle.network"] |
      del(.["scarif.priddle.network"])
  ' "$FEEDS/ssl/scarif.json.tmp" | tee "$FEEDS/ssl/star.json.tmp"
} |
  jq -s add |
  tee "$FEEDS/ssl/status.json.tmp"

mv -f "$FEEDS/ssl/router.json.tmp" "$FEEDS/ssl/router.json"
mv -f "$FEEDS/ssl/dns1.json.tmp" "$FEEDS/ssl/dns1.json"
mv -f "$FEEDS/ssl/dns2.json.tmp" "$FEEDS/ssl/dns2.json"
mv -f "$FEEDS/ssl/scarif.json.tmp" "$FEEDS/ssl/scarif.json"
mv -f "$FEEDS/ssl/emby.json.tmp" "$FEEDS/ssl/emby.json"
mv -f "$FEEDS/ssl/star.json.tmp" "$FEEDS/ssl/star.json"
mv -f "$FEEDS/ssl/status.json.tmp" "$FEEDS/ssl/status.json"
