#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

set -euo pipefail

FEEDS=/volume1/docker/network.priddle.home/public/feeds/healthchecks

[[ ! -d "$FEEDS" ]] && mkdir "$FEEDS"

CHECKS=(
  dns1.acme
  dns1.ubnt
  dns2.acme
  scarif.acme
  scarif.openvpn
  scarif.static
)

for hc in "${CHECKS[@]}"; do
  curl -s "https://static.priddle.network/api/healthchecks/$hc" |
    jq . |
    tee "$FEEDS/$hc.json.tmp"

  mv -f "$FEEDS/$hc.json.tmp" "$FEEDS/$hc.json"

  if [[ "$(jq -r .status "$FEEDS/$hc.json")" =~ ^(up|grace)$ ]]; then
    touch "$FEEDS/$hc.up"
  else
    rm -f "$FEEDS/$hc.up"
  fi
done
