#!/usr/bin/env bash

~/.dotfiles/share/syno/tasks/static-dhcp-leases
~/.dotfiles/share/syno/tasks/static-healthchecks
~/.dotfiles/share/syno/tasks/static-openvpn
~/.dotfiles/share/syno/tasks/static-pihole
~/.dotfiles/share/syno/tasks/static-prowlarr
~/.dotfiles/share/syno/tasks/static-speedtest
~/.dotfiles/share/syno/tasks/static-ssl-check
~/.dotfiles/share/syno/tasks/static-syno
~/.dotfiles/share/syno/tasks/static-transmission
~/.dotfiles/share/syno/tasks/static-vnstat
