#!/usr/bin/env bash

CONTAINER=network.priddle.transmission
FEEDS=/volume1/docker/network.priddle.home/public/feeds/openvpn

[[ ! -d "$FEEDS" ]] && mkdir "$FEEDS"

NOW="$(date '+%F %T')"
TIME="$(date '+%-l:%M %p')"

DIG=(dig -4 ch txt whoami.cloudflare +short @1.1.1.1 +time=10)

sanitize() {
  tr -d '"'
}

openvpn_ip() {
  (docker exec "$CONTAINER" "${DIG[@]}" 2> /dev/null || echo UNKNOWN) | sanitize
}

real_ip() {
  ("${DIG[@]}" 2> /dev/null || echo UNKNOWN) | sanitize
}

rm -f "$FEEDS/up"

for cmd in openvpn_ip real_ip; do
  "$cmd" |
    jq -Rn \
      --arg type "$cmd" \
      --arg now "$NOW" \
      --arg time "$TIME" '
        . | .[$type] = input | .updated_at = $now | .updated_time = $time
      '
done | jq -s add | tee "$FEEDS/ips.json.tmp"

mv -f "$FEEDS/ips.json.tmp" "$FEEDS/ips.json"

REAL_IP="$(jq .real_ip "$FEEDS/ips.json")"
OPENVPN_IP="$(jq .openvpn_ip "$FEEDS/ips.json")"

if [[ "$OPENVPN_IP" != UNKNOWN ]] && [[ "$OPENVPN_IP" != "$REAL_IP" ]]; then
  touch "$FEEDS/up"
fi
