#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

FEEDS=/volume1/docker/network.priddle.home/public/feeds/opnsense

~/.dotfiles/share/opnsense/resource-usage | tee "$FEEDS/status.json.tmp"

mv -f "$FEEDS/status.json.tmp" "$FEEDS/status.json"
