#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

set -euo pipefail

export PATH="$HOME/.dotfiles/share/syno/tasks:$PATH"

healthchecks scarif-static-generator/start

static-dhcp-leases
static-openvpn
static-opnsense
static-opnsense-unbound
static-pihole
static-prowlarr
static-speedtest
static-ssl-check
static-syno
static-transmission
static-vnstat

healthchecks scarif-static-generator

# This comes last so we know the status of the healthcheck above
static-healthchecks
