#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

set -euo pipefail

FEEDS=/volume1/docker/network.priddle.home/public/feeds/transmission

[[ ! -d "$FEEDS" ]] && mkdir "$FEEDS"

rm -f "$FEEDS/up"

~/.dotfiles/share/transmission/stats |
 tee "$FEEDS/stats.json.tmp"

mv -f "$FEEDS/stats.json.tmp" "$FEEDS/stats.json"

touch "$FEEDS/up"
