#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

FEEDS=/volume1/docker/network.priddle.home/public/feeds/dhcp

[[ ! -d "$FEEDS" ]] && mkdir "$FEEDS"

~/.dotfiles/share/opnsense/dhcp-json |
  tee "$FEEDS/leases.json.tmp"

mv -f "$FEEDS/leases.json.tmp" "$FEEDS/leases.json"
