#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

FEEDS=/volume1/docker/network.priddle.home/public/feeds/dhcp

[[ ! -d "$FEEDS" ]] && mkdir "$FEEDS"

~/.dotfiles/share/opnsense/api dhcpv4/leases/searchLease |
  jq --arg domain priddle.network '.rows | map({
    mac,
    address,
    type,
    status,
    hostname: (
      if (.hostname | tostring) != "" then
        "\(.hostname).\($domain)"
      else
        null
      end
    ),
    description: (
      if (.descr | tostring) != "" then
        .descr
      else
        null
      end
    )
  })' | tee "$FEEDS/leases.json.tmp"

mv -f "$FEEDS/leases.json.tmp" "$FEEDS/leases.json"
