#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

set -euo pipefail

FEEDS=/volume1/docker/network.priddle.home/public/feeds/healthchecks

[[ ! -d "$FEEDS" ]] && mkdir "$FEEDS"

CHECKS=$(~/.dotfiles/share/healthchecks.io/ping --list |
  jq .checks |
  tee "$FEEDS/all.json.tmp"
)

mv -f "$FEEDS/all.json.tmp" "$FEEDS/all.json"

SLUGS=()

while IFS='' read -r line; do
  SLUGS+=("$line")
done < <(jq -r '.[] | .slug' <<< "$CHECKS")

for slug in "${SLUGS[@]}"; do
  jq --arg slug "$slug" '.[] | select(.slug == $slug)' <<< "$CHECKS" |
    tee "$FEEDS/$slug.json.tmp"

  if [[ "$(jq -r .status "$FEEDS/$slug.json.tmp")" =~ ^(up|grace)$ ]]; then
    touch "$FEEDS/$slug.up"
  else
    rm -f "$FEEDS/$slug.up"
  fi

  mv -f "$FEEDS/$slug.json.tmp" "$FEEDS/$slug.json"
done
