#!/usr/bin/env bash

# Enable debug mode
if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

set -euo pipefail

~/.dotfiles/share/syno/tasks/static-dhcp-leases
# This comes last inside the Synology Task so it pulls the HC for this mains
# script
#~/.dotfiles/share/syno/tasks/static-healthchecks
~/.dotfiles/share/syno/tasks/static-openvpn
~/.dotfiles/share/syno/tasks/static-opnsense
~/.dotfiles/share/syno/tasks/static-pihole
~/.dotfiles/share/syno/tasks/static-prowlarr
~/.dotfiles/share/syno/tasks/static-speedtest
~/.dotfiles/share/syno/tasks/static-ssl-check
~/.dotfiles/share/syno/tasks/static-syno
~/.dotfiles/share/syno/tasks/static-transmission
~/.dotfiles/share/syno/tasks/static-vnstat
