if ! has("gui_macvim") || ! has("gui_running")
  finish
endif

" Window settings {{{

" Hide toolbar and scrollbars
set guioptions-=T " toolbar
set guioptions-=r " right scrollbar always present
set guioptions-=R " right scrollback with vsplit
set guioptions-=l " left scrollbar always present
set guioptions-=L " left scrollback with vsplit
set guioptions-=e " use text tabbar

" Label/tab bar title
set guitablabel=%t
set title titlestring=%f

" Default window size
set lines=70 columns=220

" Never show tab bar
" set showtabline=1

" Use termguicolors
set termguicolors

" Use 256 colors
set t_Co=256
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Use light background
set background=light

" }}}

" Other settings  {{{

" Highlight the current line
set cursorline

" Enable alt key as meta key
set macmeta

" Set window transparency to 20%
"set transparency=2

" HACK: disables audio bell by enabling visual bell which doesnt work in
" macvim right now
set visualbell

" Set default font
set guifont=.AppleSystemUIFontMonospaced-Regular:h11

" Disable blinking cursor
set gcr=a:blinkon0

" }}}

" Mappings {{{

" cmd-] to shift right
nmap <D-]> >>
vmap <D-]> >gv
imap <D-]> <C-t>

" cmd-[ to shift left
nmap <D-[> <<
vmap <D-[> <gv
imap <D-[> <C-d>

" cmd-backspace: delete line
imap <D-BS> <C-u>

" cmd-/: comment/uncomment
nmap <D-/> <C-_><C-_>
vmap <D-/> <C-_><C-_>gv
imap <D-/> <C-_><C-_>

" }}}

" Include local gvim config {{{

if filereadable(expand("~/.gvimrc.local"))
  source ~/.gvimrc.local
endif

" }}}

" vim:ft=vim:ts=2:sw=2:sts=2:et
