if ! has("gui_macvim") || ! has("gui_running")
  finish
endif

" Window settings {{{

" Hide toolbar and scrollbars
set guioptions-=T
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L

" Label/tab bar title
set guitablabel=%t
set title titlestring=%f

" Default window size
set lines=70 columns=220

" Never show tab bar
set showtabline=1

" Use termguicolors
set termguicolors

" Use 256 colors
set t_Co=256
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Use light background
set background=light

" }}}

" Other settings  {{{

" Highlight column 80 and 100
set colorcolumn=80,100

" Line numbers
set number

" Highlight the current line
set cursorline

" Highlight spelling errors
set spell

" Highlight tabs and eol
set list

" Enable alt key as meta key
set macmeta

" Set window transparency to 20%
"set transparency=2

" HACK: disables audio bell by enabling visual bell which doesnt work in
" macvim right now
set visualbell

" Set default font
set guifont=Espresso\ Mono:h11

" Disable blinking cursor
set gcr=a:blinkon0

" }}}

" Mappings {{{

" cmd-] to shift right
nmap <D-]> >>
vmap <D-]> >gv
imap <D-]> <C-t>

" cmd-[ to shift left
nmap <D-[> <<
vmap <D-[> <gv
imap <D-[> <C-d>

" cmd-backspace: delete line
imap <D-BS> <C-u>

" cmd-/: comment/uncomment
nmap <D-/> <C-_><C-_>
vmap <D-/> <C-_><C-_>gv
imap <D-/> <C-_><C-_>

" Set colorcolumn for gitcommit
autocmd FileType gitcommit setl colorcolumn=72

" }}}

" Include local gvim config {{{

if filereadable(expand("~/.gvimrc.local"))
  source ~/.gvimrc.local
endif

" }}}

" vim:ft=vim:ts=2:sw=2:sts=2:et
