" Initialization {{{

" Source all files under `./vim/config/` relative to this vimrc file
let s:dotvim = resolve(fnamemodify(resolve(expand('<sfile>')), ':p:h'))

for f in split(glob(s:dotvim.'/config/**/*.vim'), '\n')
  execute "source" f
endfor

" Include local vim config
if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif

" }}}

" vim:ft=vim:ts=2:sw=2:sts=2:et:fdm=marker
