#!/usr/bin/env bash

target="$(hostname -s)"

if [[ -z "$target" ]]; then
  echo "Uh oh, couldn't determine target from hostname" >&2
  exit 1
fi

echo ~/Downloads ~/Pictures ~/Sites ~/work |
  xargs -I {} -P 5 -n 1 \
    rsync "$@" \
      --stats \
      --delete \
      --progress \
      --partial \
      --verbose \
      --compress \
      --log-file="$HOME/Library/Logs/rsync-mac.log" \
      --archive \
      -e "ssh -o Compression=no" \
      "{}" "scarif.priddle.network:/volume1/NetBackup/$target/"
