#!/usr/bin/env bash

# 2023-07-10:
# TODO: use uid?
# {"name": "Studio Display Microphone", "type": "input", "id": "58", "uid": "AppleUSBAudioEngine:Apple Inc.:Studio Display:00008030-0008586C0184802E:6,7"}
# {"name": "Studio Display Microphone", "type": "input", "id": "63", "uid": "AppleUSBAudioEngine:Apple Inc.:Studio Display:00008030-001835203EF0802E:6,7"}
# {"name": "Studio Display Speakers", "type": "output", "id": "48", "uid": "AppleUSBAudioEngine:Apple Inc.:Studio Display:00008030-0008586C0184802E:8,9"}
# {"name": "Studio Display Speakers", "type": "output", "id": "53", "uid": "AppleUSBAudioEngine:Apple Inc.:Studio Display:00008030-001835203EF0802E:8,9"}

# Output from my M2 Mac Mini
#
# SwitchAudioSource -a -f json
#
# Left Studio Display mic
# {
#   "name": "Studio Display Microphone",
#   "type": "input",
#   "id": "58",
#   "uid": "AppleUSBAudioEngine:Apple Inc.:Studio Display:00008030-0008586C0184802E:6,7"
# }
#
# Right Studio Display mic
# {
#   "name": "Studio Display Microphone",
#   "type": "input",
#   "id": "63",
#   "uid": "AppleUSBAudioEngine:Apple Inc.:Studio Display:00008030-001835203EF0802E:6,7"
# }
#
# Left Studio Display speakers
# {
#   "name": "Studio Display Speakers",
#   "type": "output",
#   "id": "48",
#   "uid": "AppleUSBAudioEngine:Apple Inc.:Studio Display:00008030-0008586C0184802E:8,9"
# }
#
# Right Studio Display speakers
# {
#   "name": "Studio Display Speakers",
#   "type": "output",
#   "id": "53",
#   "uid": "AppleUSBAudioEngine:Apple Inc.:Studio Display:00008030-001835203EF0802E:8,9"
# }
#
# Headphone jack mic
# {
#   "name": "External Microphone",
#   "type": "input",
#   "id": "105",
#   "uid": "BuiltInHeadphoneInputDevice"
# }
#
# Headphone jack speakers
# {
#   "name": "External Headphones",
#   "type": "output",
#   "id": "98",
#   "uid": "BuiltInHeadphoneOutputDevice"
# }
#
# built in Mac mini speakers
# {
#   "name": "Mac mini Speakers",
#   "type": "output",
#   "id": "92",
#   "uid": "BuiltInSpeakerDevice"
# }

SWITCH=/opt/homebrew/bin/SwitchAudioSource

RIGHT_STUDIO_MIC_UID="AppleUSBAudioEngine:Apple Inc.:Studio Display:00008030-0008586C0184802E:6,7"
RIGHT_STUDIO_SPEAKERS_UID="AppleUSBAudioEngine:Apple Inc.:Studio Display:00008030-0008586C0184802E:8,9"
EXTERNAL_HEADPHONES_UID="BuiltInHeadphoneOutputDevice"

main() {
  local device="${1-}"

  if [[ ! -x "$SWITCH" ]]; then
    echo "SwitchAudioSource is not installed" >&2
    return 1
  fi

  case "$device" in
    -h|--help|help)
      sed -ne '/^#/!q;s/^#$/# /;/^# /s/^# //p' < "$0" |
        awk -v f="${device#-h}" '!f&&/^Usage:/||u{u=!/^\s*$/;if(!u)exit}u||f'
      ;;
    external|a5)
      "$SWITCH" -u "$EXTERNAL_HEADPHONES_UID" -t output
      "$SWITCH" -u "$RIGHT_STUDIO_MIC_UID" -t input
      ;;
    studio|"")
      "$SWITCH" -u "$RIGHT_STUDIO_SPEAKERS_UID" -t output
      "$SWITCH" -u "$RIGHT_STUDIO_MIC_UID" -t input
      ;;
    *)
      echo "Invalid argument: $1" >&2
      return 1
      ;;
  esac
}

main "$@"
