#!/usr/bin/env zsh

if [ -z "$DOCKER_HOST" ]; then
  # Start docker-machine if it is not running
  [ "$(docker-machine status dev)" != "Running" ] && docker-machine start dev

  # Initializes shell for use with docker/docker-machine
  eval "$(docker-machine env dev)"
fi

# Run `docker`
command docker $@
