#!/usr/bin/env zsh

url="$(
  gcalcli agenda \
    --calendar=Work \
    --details=url \
    --tsv "$(date "+%F %T")" "$(date "+%F 23:59:59")" |
    awk -F"\t" '{ print $6; exit; }'
)"

if [[ -n "$url" ]]; then
  printf "%s\n" "$url"
else
  >&2 echo "No hangouts today!"
  return 1
fi
