#!/usr/bin/env bash

if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

set -e

CONTAINER="deluge-deluge-openvpn-1"

notify() {
  slack-notify --webhook-url "https://slack.priddle.network" "$@"
}

deluge_running() {
  sudo docker ps | grep -q "$CONTAINER"
}

stop_deluge() {
  sudo docker stop "$CONTAINER"
}

if ! deluge_running; then
  if [[ ! -f ~/.deluge-notified ]]; then
    touch ~/.deluge-notified
    notify "Deluge is not running!"
  fi
  exit 1
else
  rm -f ~/.deluge-notified
fi

real_ip=$(dig @1.1.1.1 ch txt whoami.cloudflare +short | tr -d '"')

openvpn_ip=$(sudo docker exec -t deluge-deluge-openvpn-1 dig @1.1.1.1 ch txt whoami.cloudflare +short | tr -d '"')

if [[ "$real_ip" == "$openvpn_ip" ]]; then
  stop_deluge

  notify \
    --channel "#deluge" \
    --color "F1AEB5" \
    --pretext "Deluge IP is the same as our real IP! Deluge is now shutdown" \
    --field "OpenVPN IP|$openvpn_ip" \
    --field "Real IP|$real_ip"

  touch ~/.deluge-notified

  exit 1
fi
