#!/usr/bin/env bash

token="xxxxxxxxxxxxxxxxxxxx"
server="127.0.0.1"

case "$1" in
  movies)
    id=1
    ;;
  shows)
    id=2
    ;;
  all)
    shift
    "$0" movies "$@"
    "$0" shows "$@"
    ;;
  *)
    echo "invalid option" >&2
    ;;
esac

shift

# force=1 to go nuts
if [[ "${1-}" = "--force" ]]; then
  url="$url&force=1"
fi

url="http://$server:32400/library/sections/$id/refresh?X-Plex-Token=$token"

echo "$url"
curl "$url"
