#!/usr/bin/env bash
# Usage: copy-to-plex-tmp "TorrentID" "Torrent Name" "Torrent Path"

set -euo pipefail

# "TorrentID" "Torrent Name" "Torrent Path"

if [[ $# -ne 3 ]]; then
  echo "Invalid arguments" >&2
  echo >&2
  echo "${0##*/} \"TorrentID\" \"Torrent Name\" \"Torrent Path\"" >&2
  exit 1
fi

if [[ ! -d /plex ]] || [[ ! -d /config ]]; then
  echo "This doens't look like deluge, cowardly aborting." >&2
  exit 1
fi

path="$3/$2"

if [[ ! -r "$path" ]]; then
  echo "Path '$path' does not exist" >&2
  exit 1
fi

cp -pr "$path" /plex/

plex_uid=1028 # plex
plex_gid=100  # users

chown -R "$plex_uid:$plex_gid" "/plex/$2"

if [[ -d "/plex/$2" ]]; then
  chmod 775 "/plex/$2"

  find "/plex/$2" -type f -exec chmod 644 {} \;
  find "/plex/$2" -type d -exec chmod 775 {} \;
else
  chmod 644 "/plex/$2"
fi
