#!/usr/bin/env zsh

# makes color constants available
autoload -U colors
colors

fpath=(~/.dotfiles/zsh/functions $fpath)

# Remove /usr/local/share/zsh/site-functions from $fpath
fpath=(${(@)fpath:#/usr/local/share/zsh/site-functions})

autoload -U ~/.dotfiles/zsh/functions/*(:t)

setopt NO_BGNICE
setopt NO_HUP
setopt NO_LIST_BEEP
setopt LOCAL_OPTIONS
setopt LOCAL_TRAPS

# Leave =/&; out of WORDCHARS so ^W acts more nicely
# Default: *?_-.[]~=/&;!#$%^(){}<>
WORDCHARS='*?_-.[]~\!#$%^(){}<>|`@#$%^*()+:?''`'

# emacs style keybindings
bindkey -e

# Escape special characters in URLs when pasting to the terminal
autoload -U url-quote-magic
zle -N self-insert url-quote-magic
