#!/usr/bin/env zsh

HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
REPORTTIME=10

setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS
#setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE
setopt HIST_NO_STORE
setopt HIST_NO_FUNCTIONS
setopt NO_HIST_BEEP
setopt HIST_SAVE_NO_DUPS

autoload -U history-search-end

zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

bindkey '\e[A'   history-beginning-search-backward-end
bindkey '\e[B'   history-beginning-search-forward-end

bindkey '^k'   history-beginning-search-backward-end
bindkey '^j'   history-beginning-search-forward-end

# Make `history` behave more like bash
history() {
  if [[ $# -eq 0 ]]; then
    builtin history 1
  else
    builtin history $*
  fi
}
