#!/usr/bin/env bash

if [ -f /usr/local/etc/bash_completion ]; then
  source /usr/local/etc/bash_completion
fi

for script in $HOME/.dotfiles/bash/completion.d/*
do
  source $script
done

# Case insensitive completion
bind 'set completion-ignore-case on'

# Show matches on ambiguous completion
bind 'set show-all-if-ambiguous on'
