#!/usr/bin/env bash

for script in $HOME/.dotfiles/bash/completion.d/*
do
  [ -f "${script}" ] && source "${script}"
done
unset script

# Case insensitive completion
bind 'set completion-ignore-case on'

# Show matches on ambiguous completion
bind 'set show-all-if-ambiguous on'
