#!/usr/bin/env bash

# Disable new mail check
shopt -u mailwarn
unset MAILCHECK

if [ "${OSTYPE:0:6}" != "darwin" ] && [ -f /etc/bashrc ]; then
  source /etc/bashrc
fi

# Store nullglob state
shopt -q nullglob && old_nullglob=1
shopt -s nullglob

# Source plugin files
for plugin in ~/.dotfiles/bash/plugins/*
do
  [ -f "${plugin}" ] && source "${plugin}"
done

# Restore nullglob state
[ "${old_nullglob:-}" ] && shopt -u nullglob

# Cleanup
unset plugin old_nullglob

# History
export HISTCONTROL=ignoredups
export HISTFILESIZE=5000
export HISTSIZE=5000

# check the window size after each command and, if necessary, update the
# values of LINES and COLUMNS.
shopt -s checkwinsize

# append to the history file, don't overwrite it
shopt -s histappend

# search history with up/down, filters by command line contents
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Write history immediately
export PROMPT_COMMAND="history -a; history -n${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
