#!/usr/bin/env bash

# Disable new mail check
shopt -u mailwarn
unset MAILCHECK

if [ -f /etc/bashrc ]; then
  source /etc/bashrc
fi

for plugin in $HOME/.dotfiles/bash/plugins/*
do
  source $plugin
done
unset plugin

# History
export HISTCONTROL=ignoredups
export HISTFILESIZE=5000
export HISTSIZE=5000

# check the window size after each command and, if necessary, update the
# values of LINES and COLUMNS.
shopt -s checkwinsize

# append to the history file, don't overwrite it
shopt -s histappend

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Write history immediately
export PROMPT_COMMAND="history -a"
