#!/usr/bin/env bash

# "%": untracked files in repo
# export GIT_PS1_SHOWUNTRACKEDFILES=1

# "+": staged
# "*": unstaged
export GIT_PS1_SHOWDIRTYSTATE=1

# "$": something stashed
# export GIT_PS1_SHOWSTASHSTATE=1

_josh_prompt_command() {
  local blue="\[\e[1;34m\]"
  local green="\[\e[1;32m\]"
  local yellow="\[\e[1;33m\]"
  local reset="\[\e[0m\]"

  local git_tmp=$(__git_ps1 " (%s)" 2> /dev/null)

  local git= host=

  if [ "$SSH_CONNECTION" ]; then
    host="${yellow}\u@\H${reset} "
  fi

  if [ "$git_tmp" ]; then
    git="${green}${git_tmp}${reset}"
  fi

  local pat=$(printf '/*%.0s' {1..3})
  local cwd=${PWD/$HOME/\~}
  local tmp=${cwd%$pat}

  if [ ${#tmp} -gt 0 -a "$tmp" != "$cwd" ]; then
    prompt_cwd=$(printf "${cwd:${#tmp}+1}")
  else
    prompt_cwd=$(printf "$cwd")
  fi

  PS1="${host}${blue}${prompt_cwd}${reset}${git} $ "

  case "$TERM" in
    xterm*|rxvt*)
      PS1="${PS1}\e]0;${SSH_CONNECTION:+\u@\M:}\w\a"
      ;;
  esac
}

export PROMPT_COMMAND="$PROMPT_COMMAND; _josh_prompt_command"
