#!/usr/bin/env bash

prompt_pwd() {
  local pat=$(printf '/*%.0s' {1..3})
  local cwd=${PWD/$HOME/\~}
  local tmp=${cwd%$pat}

  if [ ${#tmp} -gt 0 -a "$tmp" != "$cwd" ]; then
    printf "${cwd:${#tmp}+1}"
  else
    printf "$cwd"
  fi
}

export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWDIRTYSTATE=1

set_prompt() {
  local BLUE="\[\033[1;34m\]"
  local GREEN="\[\033[1;32m\]"
  local YELLOW="\[\033[1;33m\]"
  local NOCOLOR="\[\033[0m\]"

  local git_tmp=$(__git_ps1 2> /dev/null)

  local GIT= HOST=

  if [ "$SSH_CONNECTION" ]; then
    HOST="${YELLOW}\u@\H${NOCOLOR} "
  fi

  if [ "$git_tmp" ]; then
    GIT="${GREEN}${git_tmp}${NOCOLOR}"
  fi

  PS1="${HOST}${BLUE}$(prompt_pwd)${NOCOLOR}${GIT} $ "

  case "$TERM" in
    xterm*|rxvt*)
      PS1="$PS1\e]0;${SSH_CONNECTION:+\u@\h:}\w\a"
      ;;
  esac
}

export PROMPT_COMMAND=set_prompt
